// auth
export const REQUESTING_AUTH_DATA = 'REQUESTING_AUTH_DATA';
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';
export const GET_USER = 'GET_USER';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const SHOW_REGISTER = 'SHOW_REGISTER';
export const SHOW_LOGIN = 'SHOW_LOGIN';

// exercises
export const REQUESTING_EXERCISES_DATA = 'REQUESTING_EXERCISES_DATA';
export const RECEIVED_EXERCISES_DATA = 'RECEIVED_EXERCISES_DATA';
export const GET_EXERCISES = 'GET_EXERCISES';
export const NEW_EXERCISE = 'NEW_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';

// workouts
export const REQUESTING_WORKOUTS_DATA = 'REQUESTING_WORKOUTS_DATA';
export const RECEIVED_WORKOUTS_DATA = 'RECEIVED_WORKOUTS_DATA';
export const GET_WORKOUTS = 'GET_WORKOUTS';
export const NEW_WORKOUT = 'NEW_WORKOUT';
export const EDIT_WORKOUT = 'EDIT_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const ADD_TO_WORKOUT = 'ADD_TO_WORKOUT';
export const EDIT_WORKOUT_EXERCISE = 'EDIT_WORKOUT_EXERCISE';
export const REMOVE_WORKOUT_EXERCISE = 'REMOVE_WORKOUT_EXERCISE';

// display
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL_NEW = 'SHOW_MODAL';
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL';
export const SHOW_ADD_TO_WORKOUT = 'SHOW_ADD_TO_WORKOUT';
export const SHOW_EDIT_WORKOUT = 'SHOW_EDIT_WORKOUT';
export const SHOW_EDIT_WORKOUT_EXERCISE = 'SHOW_EDIT_WORKOUT_EXERCISE';
export const SHOW_EDIT_EXERCISE = 'SHOW_EDIT_EXERCISE';
export const VIEW_WORKOUT = 'VIEW_WORKOUT';
export const BACK_TO_DASHBOARD = 'BACK_TO_DASHBOARD';
export const DISPLAY_WORKOUTS = 'DISPLAY_WORKOUTS';
export const DISPLAY_EXERCISES = 'DISPLAY_EXERCISES';

// details
export const SET_DELETABLE_EXERCISE = 'SET_DELETABLE_EXERCISE';
export const SET_DELETABLE_WORKOUT = 'SET_DELETABLE_WORKOUT';
export const SET_WORKOUT_TO_ADD_TO = 'SET_WORKOUT_TO_ADD_TO';
export const SET_WORKOUT_TO_EDIT = 'SET_WORKOUT_TO_EDIT';
export const SET_WORKOUT_EXERCISE_TO_EDIT = 'SET_WORKOUT_EXERCISE_TO_EDIT';
export const SET_EXERCISE_TO_EDIT = 'SET_EXERCISE_TO_EDIT';
export const SET_WORKOUT_TO_VIEW = 'SET_WORKOUT_TO_VIEW';
export const RESET_WORKOUT_TO_VIEW = 'RESET_WORKOUT_TO_VIEW';
export const RESET_ALL_DETAILS = 'RESET_ALL_DETAILS';
export const RESET_WORKOUT_EXERCISE_TO_EDIT = 'RESET_WORKOUT_EXERCISE_TO_EDIT';

// util
export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const SET_FETCHING = 'SET_FETCHING';
export const UNSET_FETCHING = 'UNSET_FETCHING';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';