// auth
export const REQUESTING_AUTH_DATA = 'REQUESTING_AUTH_DATA';
export const RECEIVED_AUTH_DATA = 'RECEIVED_AUTH_DATA';
export const GET_USER = 'GET_USER';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const SHOW_REGISTER = 'SHOW_REGISTER';
export const SHOW_LOGIN = 'SHOW_LOGIN';

// exercises
export const REQUESTING_EXERCISES_DATA = 'REQUESTING_EXERCISES_DATA';
export const RECEIVED_EXERCISES_DATA = 'RECEIVED_EXERCISES_DATA';
export const GET_EXERCISES = 'GET_EXERCISES';